### ISSUE TITLE
[BUG] Function definitions inside headers are not `inline`.

### ISSUE THREAD

**Issue by automaticp** [dario-loi/glcore#1]
**Describe the bug**
Definitions of member functions inside headers should be marked [`inline`](https://en.cppreference.com/w/cpp/language/inline). They're only implicitly inline if they are contained within the class definition body, are templates (not full specializations), or marked constexpr.  Applies to member functions of vertex buffer wrappers, framebuffer wrappers, etc. Haven't looked at all the code, but it's probably consistently missing.

**To Reproduce**
1. Create 2 `.cpp` files;
2. Include any header in both;
3. Compile and link;
4. See ODR violation.

**Expected behavior**
\*Happy linker noises\*

**Desktop (please complete the following information):**
 - Haven't actually tried this on a machine, but it's an ODR-violation even when I just think about it.

**Additional context**
Clang-tidy is heavily recommended. Catches this immediately.

**Comment by dario-loi** [comment]
You are right, this is such an obvious error but I did not spot it. I'm also running `clang-tidy` checks occasionally but they seem to never have caught these things, maybe the custom command is misfigured?

I will ship a fix ASAP.


P.S, Do you happen to know of any way to enable `clang-tidy` project-wide on CMake *without* having it check every target? I previously had it integrated that way but it spent minutes trying to apply FIX-ITs to GLAD, breaking the loader in the process.

**Comment by automaticp** [comment]
> maybe the custom command is misfigured?

`misc-definitions-in-headers` is what you're looking for.

> P.S, Do you happen to know of any way to enable clang-tidy project-wide on CMake without having it check every target? I previously had it integrated that way but it spent minutes trying to apply FIX-ITs to GLAD, breaking the loader in the process.

The external libraries should be their own `IMPORTED` targets and be linked against by the example applications. Do not add their include directories [like this](https://github.com/dario-loi/staplegl/blob/afd440ed85b0e94ab88ba402d42cf5694cf8105b/CMakeLists.txt#L61). Instead, create an imported target that represents glad:
```cmake
add_library(glad STATIC IMPORTED)
target_sources(glad PRIVATE ${GLAD_SOURCES})
target_include_directories(glad PUBLIC ${GLAD_INCLUDE_DIR})
```
And then link:
```cmake
target_link_libraries(sandbox PRIVATE glad)
```

Then ask CMake to generate `compile_commands.json` by passing `-DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE` when invoking cmake. 

This should convince cmake that glad is an external target and will generate correct include/link flags inside `compile_commands.json`, which will then be picked up by clang-tidy as stuff to ignore.

Also this might not work, since I haven't exactly tried this, and cmake is, well, cmake. Unpredictable with its rules at times. 

Also also probably don't blindly run clang-tidy fixes, just ask it to list all warnings instead, and then vet them manually.

**Comment by dario-loi** [comment]
I patched the clang tidy scripts manually to make them work and got rid of all ODR violations, I am in the process of ironing out some more warnings that turned up when the checks started working and I will shortly be pushing a fix.

Thank you for the insight on CMake, I'll try and clean the build system up next.

**Comment by automaticp** [comment]
> Instead, create an imported target that represents glad:

Or maybe that won't work because you can't *build* IMPORTED targets and you'll have to do a switcheroo with an extra target:
```cmake
add_library(glad_impl STATIC)
target_sources(glad_impl PRIVATE ${GLAD_SOURCES})
target_include_directories(glad_impl PUBLIC ${GLAD_INCLUDE_DIR})

add_library(glad::glad IMPORTED INTERFACE)
target_link_libraries(glad::glad INTERFACE glad_impl)

# And then, finally...

target_link_libraries(sandbox PRIVATE glad::glad)
```

Keep in mind that I wrote like 10 lines of cmake and my head already hurts. So, uh, have fun figuring this out! Still no guarantees that *this* will work, sorry.

**Comment by dario-loi** [comment]
I appreciate the effort man, maybe we should just KISS and keep the custom commands, `-header-filter=${STAPLEGL_HEADERS}` seems to be working for me.
